### ISSUE TITLE
Vollmer - PPoPP 2017

### ISSUE THREAD

**Issue by cgswords** [wonks/Talk_Rehearsal_Feedback#3]
Put comments here!

**Comment by RyanGlScott** [comment]
* Slide 10: To reinforce the point in the previous slide, give the type of the code in this slide (`IO Int`). Especially since you give the type of similar code in slide 12.
* Slide 13: Perhaps give a code example using `STM` and `TVar` analogous to slides 10 and 12.
* Slide 22: There's a bit of text overload here. Perhaps put the read rules and the write rules on different slides? Also consider making the text size a little larger, since I imagine it can be hard to read the `IO`, `STM`, etc. underneath the reduction rule arrow.
* Slide 27: I don't think you ever stated what an `MVar` is before this slide!
* Slide 28: Oh, you define it here. I suppose that's acceptable :)
* Slide 37: Do we have the ability to put labels on these axes?

**Comment by cgswords** [comment]
Timing:

| minutes | slide # |
|---------|---------|
| 2  | 5 |
| 4 | 8 |
| 6 | 11 |
| 8 | 13 |
| 10 | 17 |
| 12 | 20 |
| 14 | 22 |
| 16 | 28 |
| 18 | 32 |
| 20 | 35 |
| 22 | 40 |

**Comment by cgswords** [comment]
general notes:

 - grounded examples would be much nicer (`IORef Int` vs `IORef a`)
- slide 16 has a lot of big terms that you skate through without explaining -- just drop 'em?
- slide 20 is technical, but can lose people easily
- just pick a single case study and use that; you don't need both
- the phrase 'universally quantified" will *lose* your audience outright
- the language presentation should get more space, be easier to read throughout

**Comment by pnwamk** [comment]
Slide 4 -- you describe some non-intuitive thing that could happen because of hardware -- it would have been nice if you had illustrated that briefly on the slide (like how you illustrated where the barriers would go).

Slide 17 is screwed up -- I think it may have been screwed up when you changed the theme.

You're having to use your laser to point at small things while your talking about them (e.g. slide 19). If you want to do that that's fine, but if you're worried that might be annoying during your actual PPoPP talk, it might be nice to instead have transitions that bold/highlight the pieces your talking about. Just a thought.

**Comment by vikraman** [comment]
Do the programs in the benchmarks do the same thing as before after compiling with sc-ed ghc?

**Comment by cgswords** [comment]
circle feedback

- mention that adding it to GHC was easy
- what engineering changed had to happen in the case studies? explain
- interesting to see haskell code verified by runtime checks :)
- motivating the problem took a while to click
- nice identifying stats method!
- first example was a lie
- don't ask questions at the end, say 'thanks'
- don't say 'this is the hardest haskell, and it's easy' -- don't assign a difficulty rating
- it was jarring to start talking about 'slowdown' sort of out of the blue
- some middle ground between 'hardcore judgment rules' and 'it's in the paper'
- you need to spend time on *the theorem*
- don't put four rules on the same slide

**Comment by cgswords** [comment]
graphics would go a long way; there were a lot of slides where you had bullet points and then followed up with an image that explains it afterwards -- skip the bullet points
