### ISSUE TITLE
2017 OOPSLA - Ryan Scott, Monadic Composition for Deterministic, Parallel Batch Processing

### ISSUE THREAD

**Issue by samth** [wonks/Talk_Rehearsal_Feedback#6]

**Comment by vikraman** [comment]
The title slide has weird alignment.

**Comment by samth** [comment]
Slide 3 looks like the different outputs are all produced at once.

**Comment by samth** [comment]
Can you have a lot of screenshots of these sort of github issues, instead of just one?

**Comment by vikraman** [comment]
The non-deterministic make output transition was too fast.

**Comment by samth** [comment]
Yeah the make syntax was hard to understand.

**Comment by samth** [comment]
The "detflow" slide features you saying lots of things that aren't on the slide.

**Comment by vikraman** [comment]
... but haskell has side-effects besides IO! (exceptions, laziness, nontermination, etc.). Is this a subset of Haskell?

**Comment by samth** [comment]
Avoid having to go back in slides.

**Comment by vikraman** [comment]
th1/t1 typo

**Comment by samth** [comment]
I wonder how this compares with Shill, a system for capability-based shell-like scripting.

**Comment by vikraman** [comment]
Are those the _only_ banned directories? Because there should be more...

**Comment by samth** [comment]
Do you really remove concurrency? Can't that create deadlocks?

**Comment by vikraman** [comment]
You said ALSR instead of ASLR.

**Comment by samth** [comment]
24:45 time without questions.

**Comment by rrnewton** [comment]
This presentation doesn't really *introduce* determinism... it kind of
assumes that the user already wants to achieve determinism.

Our "goal is to make it easier to do this"... I disagree!... our job is
to make programs *run as deterministic by default*, which is not quite
the same thing as making it incrementally easier in some continuous
space of easiness.

"make -j".. Slightly awkward that what you are calling "Answers" is
the printed stdout.  With normal makefiles output files are the answer
people care about.

"detflow" slide: "low overall overhead" seems like it's different than
the others, and applies to both, thus it could have a different shape.
Ah, I see, this is used as the roadmap.

If you are going to have tiltes, the one word titles don't convey that
much information.  What does "Entrypoints" mean?  I'm not sure if
that's a word that was spoken.

Showing the DEFINITION of the DetIO type does not seem important.
Further, it's INCOMPLETE (the real one is a state transformer over
IO), so why show it?

Wait... when we switched from IO to DetIO... the example changed too.
We didn't see the original "print 1 to 10" program again, did we?

"uses the filesystem for shared-meory parallelism" doesn't parse.
Do you mean "detflow allows multithreaded access to the file system"?

convoluted language around "RW 1.0".. suggested:
  "only on thread in the system can hold full write permission on a given path", OR
  "if one thread has full write permission on a path, then every other
   thread in the system must have zero permission"

Type signatures are less fun to read than the simple example programs
for most of the audience (esp. the majority of the audience that
doesn't write -- or often read -- Haskell).

"More detflow" -- This seems to be talking about the static version
only... seems like we lost the FFI/legacy program bit for a while.

Yet short examples like this are easy to fit in:

    system "gcc -c foo.c"

And they are a reminder that DetIO must handle these subprocesses
seamlessly.

Ah... the "system calls" slide introduces "system".

Interecpts calls from libc that "might be problematic when you're
running things".  Even if you use the word "determinism" until you're
sick of it, probably better to just say "determinism" instead of "not
problematic".

This could do with something more like a system architecture diagram
(rather than the abstract 3 shapes).

So far there isn't that much clear expectation of what comes
next.. lot's of surprising turns.  For example, new problems keep
coming up (like ASLR), rather than laying out / foreshadowing the
problems up front and

"ran ... make AGAINST SPLASH2"... wrong word.  Used Make to *build*
SPLASH2 benchmarks.

Make benchmarks:
The plots themselves are not that interesting so they could be on the
same slide as the previous discussion.

The Raxml hiccup -- it's an interesting thing to point out but we
could probably do it more concisely.

"Pedigree style of printing" .. I don't think you defined/covered
that.

"most programs don't work this way" - you usually "dynamically check
out permissions" -- but haven't said enough for it to be clear to the
viewer what this dynamic checkout would mean.  I think you're falling
back on some of our internal lingo from our discussions with
collaborators, but of course the audience isn't in our heads.

------------

Big picture:  This needs to tell a story better.  One story.

The paper has a problem that the technical solutions aren't
individually deep or novel, it's just their particular combination in
this application that is interesting.  Example: The details of
fractional permissions are not THAT interesting.

The flow of permissions between DetIO and the dynamic sandboxes IS
kind of interesting/elegant.  As of the "lidbdet" slide I don't think
that's bene highlighted.  The slide with 'system "gcc"' went by
quickly.

Conference Questions:
---------------------

<Q> How does this relate to "deny capabilities"?

<Q> SamTH: when you say "sequentially", can't that produce deadlock
fairly easily?

[RyanN: I think we should forestall the deadlock / sequential
scheduling thing with a brief comment during the main talk.]

Not good to waffle on this one -- we need to make clear that the
current scheduling thing is a rough prototype and yes, deadlocks on
programs that we should be able to support.  EASY (conceptually) to
define better sequential scheduling.

<Q> Kyle: about ASLR

<Q> Buddhika: do you have any real guarantee that mmap will be
deterministic without ASLR.

Answer: just experimental observation.

(Potential answer... we could get more bossy with MAP_FIXED on
linux. But still, the program would need to fail if the OS wouldn't
yield the desired addresses.)

<Q>: ChrisW: what if you fill up the hard disk and then run it again?

ChrisW: If you want reproducible performance... issues with memory
access time.

(But I don't think he's directly asking about the program in the jail
observing these nondeterministic performance effects.)

<Q>: Aaron Hsu: so you can't compose this system with other
concurrency models.

Answer: there are other deterministic parallelism libraries "that
would work just as well here".  [RN: I don't like the wording.  Makes
it seem like an ALTERNATiVE.  These other things can be used WITH
DETIO, because they're dischargable effects.]

But the short answer is that you can allow all models of deterministic
parallelism... as long as it's Haskell.  The anwser about dthreads is
good if you want to have parallel leaf processes.


Other comments:
------------

Omar: mentions several topics.  Mentions quasideterminism being relevant.
Mentions libdet inheriting permissions.
