### ISSUE TITLE
Andre - SFP 2018

### ISSUE THREAD

**Issue by samth** [wonks/Talk_Rehearsal_Feedback#9]

**Comment by RyanGlScott** [comment]
I would consider shortening the beginning of the talk, which goes through several prerequisite details (space efficiency, naive proxies, etc.) in perhaps more detail than is necessary before arriving at discussion of the compiler itself. If need be, you can always revisit each of these topics in other parts of the talk, especially since you have a slide which states that the goals of the compiler are to address these problems.

**Comment by RyanGlScott** [comment]
It might be worth highlighting (in a different color scheme) which compiler passes are the most important/novel ones. (I think you state this aloud, but having it on the slide would help reinforce this.)

**Comment by RyanGlScott** [comment]
Briefly, state what a "monotonic reference" is. (It wasn't clear to me.)

**Comment by samth** [comment]
- What's the key idea or two technical ideas you want to communicate?
- What's the takeaway you want your audience to learn?

Decide those, then write your talk around them.

**Comment by RyanGlScott** [comment]
Ah, I didn't realize that Proxied Grift and Monotonic Grift were two different compilation modes entirely! Did you state this somewhere (before the slides with the performance charts)?

**Comment by RyanGlScott** [comment]
Do you have a "*tl;dr* statistic" that states what the overall overhead of Grift is? It might be worth saying this early on, to help the audience contextualize what kind of performance to expect.

**Comment by RyanGlScott** [comment]
You said this aloud, but I'll write it down here for posterity: some of the graphs say "type-based cast" instead of "naive proxy".
